# action.yml
name: 'Terraform Enterprise API Actions'
description: 'Create Workspace, Upload Code and Run'
inputs:
  terraformHost:
    description: 'Terraform Cloud Token.'
    required: true
  terraformToken:
    description: 'Terraform Cloud Token.'
    required: true
  terraformOrg:
    description: 'Terraform Cloud Organization.'
    required: true
  terraformWorkspace:
    description: 'Terraform Cloud Workspace.'
    required: true
  configFilePath:
    description: 'Config (.tar.gz) to upload.'
    required: true
  terraformVariables:
    description: 'Terraform variables'
    required: true
  sentinelPolicySetId:
     description: 'Sentinel PolicySetId.'
     required: true
  Client_Id:
     description: 'ARM_CLIENT_ID'
     required: true
  Secret_Id:
     description: 'ARM_CLIENT_SECRET'
     required: true
  Tenant_Id:
     description: 'ARM_TENANT_ID'
     required: true
  Subscription_Id:
     description: 'ARM_SUBSCRIPTION_ID'
     required: true
  pipelineConfigFile:
     description: 'pipelineConfigFile'
     required: true
  environment:
     description: 'environment'
     required: true
runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'play'  
  color: 'green'